verbose: false
reporting:
    reports:
        - lcov
        - json
        - text
check:
    global:
        statements: 80
        branches: 80
    each:
        statements: 80
        branches: 80
